CREATE TABLE IF NOT EXISTS programs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  program_name VARCHAR(255) NOT NULL,
  start_date DATE,
  end_date DATE,
  max_participants INT NOT NULL,
  current_enrollments INT NOT NULL,
  assigned_mentors INT NOT NULL,
  status VARCHAR(20) NOT NULL
);
